import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Center } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TITLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <div className={styles.grid}>
            <Link href="/items">
            <a className={styles.card}>
              <h2>Items &rarr;</h2>
            </a>
            </Link>

            <Link href="/manage">
            <a className={styles.card}>
              <h2>Manage &rarr;</h2>
            </a>
            </Link>
            <Link href="/login">
            <a className={styles.card}>
              <h2>Login &rarr;</h2>
            </a>
            </Link>
            <Link href="/register">
            <a className={styles.card}>
              <h2>Register &rarr;</h2>
            </a>
            </Link>
          </div>
        </Center>
      </main>
    </div>
  );
};

export default Home;
